---
apiVersion: v1
kind: Service
metadata:
  name: leaforg-mysql
  labels:
    app: leaforg
spec:
  ports:
    - port: 3306
  selector:
    app: leaforg
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: leaforg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1    
kind: Deployment
metadata:
  name: leaforg-mysql
  labels:
    app: leaforg
spec:
  selector:
    matchLabels:
      app: leaforg
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: leaforg
        tier: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: leaforg-app-secret
                  key: db_root_password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: leaforg-app-secret
                  key: db_database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: leaforg-app-secret
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: leaforg-app-secret
                  key: db_password 
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim