apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-quest-pv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: mysql-disk-quests
    fsType: ext4
