apiVersion: v1
kind: Service
metadata:
  name: leaforg-redis
  labels:
    app: leaforg
    tier: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: leaforg
    tier: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaforg-redis
  labels:
    app: leaforg
    tier: redis
spec:
  selector:
    matchLabels:
      app: leaforg
      tier: redis
  template:
    metadata:
      labels:
        app: leaforg
        tier: redis
    spec:
      containers:
      - name: redis
        image: icr.io/leaforg/redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
      imagePullSecrets:
        - name: leaforg-secretss